name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write         # allow this workflow to push to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jaff0040
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output         # files will be pushed here
          build_dir: dist               # publish the 'dist' folder
          commit_message: "chore: update snake"
          force_orphan: true            # good for first-time publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
